remote_theme: pages-themes/merlot@v0.2.0

plugins:
  - jekyll-remote-theme

title: Chloe Collier Allen
description: Personal website

header_pages:
  - index.md
  - cv.md
  - research.md
  - contact.md

github:
  is_project_page: false
  is_user_page: true
